### ISSUE TITLE
Create fallback solution for latest news widget

### ISSUE THREAD

**Issue by b-m-f** [canonical-web-and-design/jp.ubuntu.com#130]
## Summary

When the latest news fail to load  (JS is disabled?) we need to find an acceptable fallback solution

## Screenshot

![image](https://user-images.githubusercontent.com/2843450/56195450-e9de5380-602c-11e9-8abb-e86fbdb21bb5.png)

**Comment by anasereijo** [comment]
@pmahnke and I discussed this and we think the best solution is to hide this section as the user can't see the blog without JavaScript.
