### ISSUE TITLE
Related articles redirect to 404s if not jp.

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/jp.ubuntu.com#136]
# Should have japanese related posts

![image](https://user-images.githubusercontent.com/2707508/56662479-fa7d7200-669b-11e9-8b88-6b0c35fdd7b8.png)

**Comment by b-m-f** [comment]
Fixed from https://github.com/canonical-web-and-design/jp.ubuntu.com/pull/138 for now.

Still needs discussion about alternative fix, going on in:
https://github.com/canonical-web-and-design/cn.ubuntu.com/issues/321

**Comment by anasereijo** [comment]
@tbille @b-m-f is this still on going?

**Comment by tbille** [comment]
This seems to be fix with the latest versions of blog
