### ISSUE TITLE
Related posts not translated

### ISSUE THREAD

**Issue by b-m-f** [canonical-web-and-design/jp.ubuntu.com#137]
## Summary

Needs translations for english words

![image](https://user-images.githubusercontent.com/2843450/56662582-3fa1a400-669c-11e9-8154-421a04088e27.png)

**Comment by anasereijo** [comment]
@b-m-f should this be in an epic?

**Comment by b-m-f** [comment]
@anasereijo could stay an issue. All that is needed is a translation for `Related posts` :)

**Comment by anasereijo** [comment]
@caldav is this something you can help us with?
