### ISSUE TITLE
ESM (Extended Security maintenance) doesn't mention to 14.04 LTS yet

### ISSUE THREAD

**Issue by nobuto-m** [canonical-web-and-design/jp.ubuntu.com#152]
## Summary

ESM is currently available for both Ubuntu 12.04 LTS and 14.04 LTS. However the page only mentions to 12.04 LTS. The ESM part should be updated to include 14.04 LTS as well.

## Process

Access to:
https://jp.ubuntu.com/enterprise-support#esm

## Current and expected result

Current: 12.04 LTS is mentioned
Expected: both 12.04 LTS and 14.04 LTS will be mentioned like https://ubuntu.com/esm

## Screenshot

![image](https://user-images.githubusercontent.com/4356209/59343219-4e284580-8d46-11e9-8e73-7051ae2ad87a.png)

**Comment by pmahnke** [comment]
@MeltySnow can you update the [copy](https://docs.google.com/document/d/1xmk7zYUzWILnbW3RxGtC9c9stYYEFtKBytETlIgyHYE/edit)
