### ISSUE TITLE
[Whitepaper - Japan] Robotics - Build takeover and engage page

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/jp.ubuntu.com#178]
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/spreadsheets/d/1-t6Lz_1sMnToPL8bdd_7alz9CTZyWlqcZ8E8YJq2BAo/edit#gid=0) and [design](https://app.zenhub.com/workspaces/web-squad-5931746dba512f05402b61f6/issues/canonical-web-and-design/web-squad/1818):
 
- [x] build takeover
- [x] build engage page
- [ ] add takeover to `/takeovers/index.html`
- [x] add takeover to `/index.html`
- [ ] add engage page to `/engage/index.html`
- [ ] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

**Comment by anasereijo** [comment]
no pdf but if you're free you can start building it https://github.com/canonical-web-and-design/web-squad/issues/1818
