### ISSUE TITLE
No custom 404 page any longer

### ISSUE THREAD

**Issue by nobuto-m** [canonical-web-and-design/jp.ubuntu.com#209]
## Summary

When accessing a page which doesn't exist, we get a bare minimum error page from the server instead of a custom error page with the website theme.

## Process

Access https://jp.ubuntu.com/does-not-exist

## Current and expected result

Current - no header, just with a bare minimum error message
Expected - a themed and custom 404 page based on: https://github.com/canonical-web-and-design/jp.ubuntu.com/blob/master/templates/404.html

## Screenshot

[Current]
![Screenshot from 2020-04-29 17-22-37](https://user-images.githubusercontent.com/4356209/80575465-9d4e9600-8a3e-11ea-81b9-23b148778859.png)
 
[Expected (ubuntu.com as an example)]
![Screenshot from 2020-04-29 17-26-25](https://user-images.githubusercontent.com/4356209/80575487-a3447700-8a3e-11ea-9e07-12497a7b0195.png)

**Comment by carkod** [comment]
Seems to be fixed. https://jp.ubuntu.com/not-found
