### ISSUE TITLE
Update webinar engage pages

### ISSUE THREAD

**Issue by AmberCharitos** [canonical-web-and-design/jp.ubuntu.com#306]
## Summary

Webinar engage pages are structured as if for a whitepaper, with a download form which leads to a 404 page. This form should be removed when the type of content is webinar, ideally through use of [this](https://discourse.ubuntu.com/t/engage-pages-and-takeovers-for-jp-ubuntu-com/21103) tool

Example page: https://jp.ubuntu.com/engage/yocto-buildroot-ubuntucore

**Comment by AmberCharitos** [comment]
Hey @carkod any idea when this will be fixed?

**Comment by carkod** [comment]
@SirSamTumless can you schedule for someone to fix this?

**Comment by SirSamTumless** [comment]
Will you have time to look at it this iteration?
