### ISSUE TITLE
jp.ubuntu.com/blog 500 Server Error

### ISSUE THREAD

**Issue by AmberCharitos** [canonical-web-and-design/jp.ubuntu.com#320]
## Summary
![Screenshot 2021-05-24 at 15 33 13](https://user-images.githubusercontent.com/67629430/119363127-5c5a9c80-bca5-11eb-93c4-c956afdaa62e.png)

**Comment by anthonydillon** [comment]
Seems up to me. Could you check again please.

**Comment by AmberCharitos** [comment]
Odd, still not working for me - tried incognito (am using chrome if that helps?)

**Comment by anthonydillon** [comment]
Found the logs for this error: https://sentry.is.canonical.com/canonical/jp-ubuntu-com/issues/18509/?query=is%3Aunresolved
