### ISSUE TITLE
`/blog`’s paginator doesn’t use Vanilla Design System pagination pattern

### ISSUE THREAD

**Issue by fitojb** [canonical-web-and-design/jp.ubuntu.com#341]
## Summary

The paginator at the bottom of the /blog page doesn’t use the [dedicated Vanilla component](https://vanillaframework.io/docs/patterns/pagination).
Compare with ubuntu.com/blog.

## Screenshot

![image](https://user-images.githubusercontent.com/554953/130724553-bd054842-7baa-48e0-baaf-f7327424dd7f.png)

**Comment by SirSamTumless** [comment]
Thanks for flagging @fitojb! We'll get someone on it ASAP.
